---
title: "Soil"
author: "kb"
editor: visual
---

```{r, include = FALSE}
require(tidyverse)
```

```{r}
soil <- read.csv('soil.csv') %>%
  as_tibble() %>%
  #  mutate(size_cm = area*10000) %>%
  group_by(ParentMaterials, Depth) %>%
  dplyr::summarize(mean = mean(MBCugCpergDrySoil), 
                   sd = sd(MBCugCpergDrySoil), 
                   n = n(),
                   se = sd/sqrt(n)
  ) %>%
  dplyr::mutate(se = sd / sqrt(n),
         lower.ci = mean - qt(1 - (0.05 / 2), n - 1) * se,
         upper.ci = mean + qt(1 - (0.05 / 2), n - 1) * se) %>%
  #mutate_at(vars(Site), factor) %>%
  #add_column(
  #  location = c('Anakena', 'Manavai', 'Southeast')
  #) %>%
  mutate_at(vars(ParentMaterials, Depth), factor)
```

```{r}
x_labels = c("0 - 20 cm")
```

```{r}
soil.barplot <- ggplot(soil, aes(x = Depth, y = mean, fill = ParentMaterials)) +   
  geom_bar(stat = "identity", position = position_dodge(width = 0.8), width = 0.75, color = "#2b2b2b", linewidth = 0.50, alpha = 0.6) +
  geom_linerange(aes(ymin = mean, ymax = mean + se), position = position_dodge(width = 0.8), linewidth = 0.75) +
  #scale_y_continuous(limits = c(0.0, 1.0), labels = function(x) paste0(x * 100)) + 
  scale_x_discrete(expand = c(0, 1), labels = x_labels) + 
  #scale_fill_manual(breaks = c("North", "West",
  #                             "Southeast"),
  #                  values = c("red", "blue", 
  #                             "green"), 
  #                  labels = c("North", "West",
  #                             "Southeast")) +
  #facet_wrap( ~ depth2, labeller = as_labeller(label_names), dir = "v", ncol = 1) + 
  ggtitle(expression(paste(italic(" Soil")))) +
  ylab(expression(paste("MBCugCpergDrySoil"))) +
  labs(x = NULL) +
  theme(strip.text = element_text(size = 10, color = "black", hjust = 0.50),
        strip.background = element_rect(fill = "#FFFFFF", color = NA),    
        panel.background = element_rect(fill = "#FFFFFF", color = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_line(color = "#b2b2b2"),
        panel.spacing.x = unit(1, "cm"),
        panel.spacing.y = unit(0.5, "cm"),
        panel.spacing = unit(1, "lines"),
        axis.ticks = element_blank(),
        legend.position = "right",
        plot.title = element_text(size = 11),
        axis.title.y = element_text(size = 11),
        legend.title = element_blank())
```

```{r}
soil.barplot
```

```{r}
soil_full <- read.csv('soil_full.csv') %>%
  as_tibble() 
#%>%
#  group_by(ParentMaterials, Depth) %>%
#  mutate_at(vars(ParentMaterials, Depth), factor)
```

```{r}
soil_full
```

```{r}
soil.lm <- lm(MBCugCpergDrySoil ~ AveDepthcm * ParentMaterials, data = soil_full)
```

```{r}
par(mfrow = c(2, 2))
plot(soil.lm)
```

```{r}
summary(soil.lm)
```

