---
title: "Coral Size"
author: "jjh"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y %H:%M')`"
editor: visual
---

```{r, include = FALSE}
require(tidyverse)
require(plyr)
require(betareg)
require(lmtest)
require(glmmTMB)
require(boot)
require(emmeans)
require(brms)
require(mvtnorm)
require(nlme)
require(rstan)
require(VGAM)
require(car)
require(lme4)
require(Rmisc)
require(readr)
require(multcomp)
require(ggthemes)
require(multcompView)
require(flextable)
```

```{r}
poci_size <- read.csv('coral_size.csv')
```

```{r}
poci_size.gg <- read_csv("poci_size_main.csv")
```

```{r}
ggplot(poci_size.gg, aes(x = size_cm)) +
  geom_histogram(fill = "#333399") + 
  #below here is ylabel, xlabel, and main title
  ylab("Frequency") +
  xlab(NULL) +
  ggtitle(expression("Coral size " (cm**2))) +
  theme_bw() +
  facet_wrap(~ Site, ncol = 1) +
  #theme sets sizes, text, etc
  theme(axis.title.x = element_text(size = 14), 
        axis.title.y = element_text(size = 14), 
        axis.text.y  = element_text(size= 10),
        axis.text.x  = element_text(size = 12), 
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        plot.title = element_text(hjust = 0.5, size = 14),
        # change plot background, grid lines, etc (just examples so you can see)
        panel.background = element_rect(fill = "white"),
        panel.grid.minor.y = element_blank(),
        panel.grid.major = element_blank(),
        plot.background = element_rect(fill = "white"),
        legend.background = element_rect(fill = "white"),
        strip.text.x = element_text(size = 12, colour = "#FFFFFF"),
        strip.background = element_rect(fill = '#000066')
  )
```

```{r}
poci_size2 <-
poci_size %>%
  as_tibble() %>%
  mutate(size_cm = area*10000) %>%
  group_by(Site) %>%
  dplyr::summarize(mean = mean(size_cm), 
                   sd = sd(size_cm), 
                   n = n(),
                   se = sd/sqrt(n)
  ) %>%
  mutate(se = sd / sqrt(n),
         lower.ci = mean - qt(1 - (0.05 / 2), n - 1) * se,
         upper.ci = mean + qt(1 - (0.05 / 2), n - 1) * se) %>%
  mutate_at(vars(Site), factor) %>%
  add_column(
          location = c('Anakena', 'Manavai', 'Southeast')
          ) %>%
  mutate_at(vars(location), factor)
```

```{r}
poci_size2
```

```{r}
poci_size.gg <-
  poci_size %>%
  mutate(size_cm = area*10000) %>%
  as_tibble() %>%
  mutate_at(vars(Site), factor)
```

```{r}
poci_size.gg
```

```{r}
model_1.lm <- lm(size_cm ~ Site, data = poci_size.gg)
```

```{r}
model_1.lm
```

```{r}
summary(model_1.lm)
```

```{r}
par(mfrow = c(2, 2))
plot(model_1.lm)
```

```{r}
Anova(model_1.lm, type = "III")
```

```{r}
confint(model_1.lm)
```

```{r}
89+14
89+98
132+66
132+143
```

```{r}
aggregate(size_cm ~ Site, data = poci_size.gg, mean)
```

```{r}
model_1.aov <- Anova(model_1.lm, type = "III")
```

```{r}
as.data.frame(model_1.aov)
```

```{r}
flextable(model_1.aov)
```

```{r}
post_hoc.model_1.lm <- glht(model_1.lm, linfct = mcp(Site = 'Tukey'))
```

```{r}
model_1.aov <- aov(size_cm ~ Site, data = poci_size.gg)
```

```{r}
# Tukey's test
tukey <- TukeyHSD(model_1.aov)
```

```{r}
tukey
```

```{r}
# compact letter display
cld <- multcompLetters4(model_1.aov, tukey)
```

```{r}
cld
```

```{r}
poci_size3 <- 
poci_size2 %>%
  add_column(
          cld = c('a', 'b', 'c')
          ) %>%
mutate_at(vars(cld), factor)
```

```{r}
poci_size3
```

```{r}
x_labels = c("North", "West", "Southeast")
# label_names = c("8 m" = "8 m", "15 m" = "15 m", "25 m" = "25 m")
```

```{r}
poci_size.gg.barplot <- ggplot(poci_size3, aes(x = location, y = mean, fill = x_labels)) +   
  geom_bar(stat = "identity", width = 0.75, color = "black", size = 0.50, alpha = 0.6) +
  geom_linerange(aes(ymin = lower.ci, ymax = upper.ci), size = 0.75) +
  scale_y_continuous(expression(paste("Mean Colony Size ("," ", cm^2, ")")), limits = c(0, 300)) + 
  scale_x_discrete(expand = c(0, 1), labels = x_labels) + 
  scale_fill_manual(values = c("#FFC74E", "#82A5C0", "#ABC178")) +
# facet_wrap( ~ depth2, labeller = as_labeller(label_names), dir = "v", ncol = 1) + 
# ggtitle(expression(paste(italic(" Pocillopora "), "spp."))) +
  geom_text(aes(label = cld, y = upper.ci), vjust = -0.5) +
  #scale_y_log10(expression(paste("Colony Size (", cm^2, ")"), limits = c(0, 100000))) +
  labs(x = NULL) +
  theme(strip.text = element_text(size = 10, color = "black", hjust = 0.50),
        strip.background = element_rect(fill = "#FFFFFF", color = NA),    
        panel.background = element_rect(fill = "#FFFFFF", color = NA),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_line(color = "#b2b2b2"),
        panel.spacing.x = unit(1, "cm"),
        panel.spacing.y = unit(0.5, "cm"),
        panel.spacing = unit(1, "lines"),
        axis.ticks = element_blank(),
        legend.position = "none",
        plot.title = element_text(size = 11),
        axis.title.y = element_text(size = 11),
        legend.title = element_blank())
```

```{r}
poci_size.gg.barplot
```
