on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        
      - name: Set up R (needed for Rmd)
        uses: r-lib/actions/setup-r@v2

      - name: Install packages (needed for Rmd)
        run: Rscript -e 'install.packages(c("leaflet", rmarkdown", "knitr", "jsonlite", "revealjs", "knitr", "tidyverse", "plyr", "betareg", "lmtest", "glmmTMB", "boot", "emmeans", "brms", "mvtnorm", "nlme", "rstan", "VGAM", "car", "lme4", "Rmisc", "readr", "multcomp", "ggthemes", "multcompView", "xtable", "tidyr", "ordinal", "mosaic", "arm", "cowplot", "qqtest"))'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.600
      
      # add software dependencies here

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
